#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Build Dockerized IPFS Backend"
  echo -e "Usage: `basename $0`"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi

declare -r TAGNAME=$(date +%Y%m%d%H%M%S)
declare -r IMAGENAME="pinbox/ipfs"

cd "${SCRIPT_DIR}/docker"
docker build -t "${IMAGENAME}:latest" -t "${IMAGENAME}:${TAGNAME}" .
