#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Shell into IPFS Docker Container"
  echo -e "Usage: `basename $0` <server name>"
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

declare -r NAME=$1

docker exec -it "${NAME}" sh


