#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "IPFS Server Stop"
  echo -e "Usage: `basename $0` <server-name>"
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

docker stop "${IPFS_SERVER_NAME}"
docker rm "${IPFS_SERVER_NAME}"

