#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "IPFS Server Stop `basename $0`"
  echo -e "Usage: `basename $0` <server-name>"
  exit 1
}

if [ $# -ne 1 ]; then
  usage
fi

declare -r IPFS_DOCKER_TAG="latest"
declare -r IPFS_SWARM_PORT="4001"
declare -r IPFS_WS_PORT="127.0.0.1:4003"
declare -r IPFS_API_PORT="127.0.0.1:5001"
declare -r IPFS_GATEWAY_PORT="127.0.0.1:9090"

declare -r IPFS_STORAGE_BASE="${SCRIPT_DIR}/../storage"

declare -r IPFS_SERVER_NAME=$1

declare -r IPFS_STORAGE_PATH="${IPFS_STORAGE_BASE}/${IPFS_SERVER_NAME}"
declare -r IPFS_STAGING="${IPFS_STORAGE_PATH}/staging"
declare -r IPFS_DATA="${IPFS_STORAGE_PATH}/data"


echo "Starting IPFS STORAGE: '${IPFS_STORAGE_PATH}'"
echo "STAGING: '${IPFS_STAGING}'"
echo "DATA: '${IPFS_DATA}'"

mkdir -p "${IPFS_DATA}"
mkdir -p "${IPFS_STAGING}"

docker stop "${IPFS_SERVER_NAME}"
docker rm "${IPFS_SERVER_NAME}"

