#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Pinbox Backend Stop"
  echo -e "Usage: `basename $0`"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"

docker stop "${SERVER_NAME}"
docker rm "${SERVER_NAME}"

