#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage () {
  echo -e "Backend Shell"
  echo -e "Usage: `basename $0`"
  exit 1
}

if [ $# -ne 0 ]; then
  usage
fi

source "${SCRIPT_DIR}/config/constants"

docker exec -it "${IPFS_SERVER_NAME}" sh


